### PR TITLE
Adds more examples and descriptions

### PR DESCRIPTION
**Pull request by tbedford**
## Description

Adds more examples and descriptions.

* [JIRA ticket - DOC-439](https://ably.atlassian.net/browse/DOC-439)
* [JIRA ticket - DOC-425](https://ably.atlassian.net/browse/DOC-425)
* [JIRA ticket - DOC-407](https://ably.atlassian.net/browse/DOC-407)

Also:

* Move unsupported rule response to correct location.

## Checklist for OpenAPI document updates

Please ensure the following:

- [x] Version has been incremented
- [x] Tested for errors with Spectral
- [x] Optional: Load into SwaggerHub and check for errors
- [x] Ensure the document renders under ReDoc (see README for instructions on how to test locally)

## Review

* Check the diff.
* Double-check the checklist.
* All response attributes should have a description and an example.

### CODE REVIEW

**Review by marklewin — COMMENTED** [review]
This looks totally great, but I think one of the response values (in reactor rules) is missing an example, specifically `source.type` which appears as `string` but which (I believe) should be either `channel.message`, `channel.presence`, `channel.lifecycle` or `channel.occupancy`?

**Comment by tbedford** [comment]
Thanks, I missed one. I will fix later today.

**Review by marklewin — APPROVED** [review]
Tested as per checklist. Spectral returns a few warnings but no errors. Renders OK in Swagger and ReDoc. LGTM!

**Comment by tbedford** [comment]
Thanks Mark!

**Pull request merged**
