### PR TITLE
EDU-1494: Removes the spectral.yaml and package-lock.json files

### PR DESCRIPTION
**Pull request by franrob-projects**
This PR removes:

Restores Open Spec files outside of `definitions/control-v1.yaml` to pre-commit state.

- `spectral.yaml` 
- Reverts `package-json` to its pre-commit state 👉  https://github.com/ably/open-specs/commit/a3abed2a815d86434a90eeb07370a31843901aba ( I managed to commit directly to the `main` repo, thinking it would appear as a commit in this PR).

The fix relates to EDU-1466 #39

[EDU-1494: Remove files](https://ably.atlassian.net/browse/EDU-1494)

### CODE REVIEW

**Review by m-hulbert — CHANGES_REQUESTED** [review]
After the commit to main, I think this should just be deleting `.spectral.yaml`

**Comment by franrob-projects** [comment]
> After the commit to main, I think this should just be deleting `.spectral.yaml`

See 17e793c168465e31d08551b54e6a0667ab13d9b2

**Comment by m-hulbert** [comment]
> > After the commit to main, I think this should just be deleting `.spectral.yaml`
> 
> See [17e793c](https://github.com/ably/open-specs/commit/17e793c168465e31d08551b54e6a0667ab13d9b2)

This is still editing all three 🙂

**Comment by franrob-projects** [comment]
> > > After the commit to main, I think this should just be deleting `.spectral.yaml`
> > 
> > 
> > See [17e793c](https://github.com/ably/open-specs/commit/17e793c168465e31d08551b54e6a0667ab13d9b2)
> 
> This is still editing all three 🙂

See: ee4a6940557fa725f41a390194c3e3e26ead0e26 @m-hulbert

**Pull request closed without merging**
