### PR TITLE
Add rule source patch and channel.occupancy

### PR DESCRIPTION
**Pull request by tbedford**
## Description

- [x] add rule source patch section https://ably.atlassian.net/browse/DOC-389
- [x] add channel.occupancy https://ably.atlassian.net/browse/DOC-405
- [x] add unsupported rule schema https://ably.atlassian.net/browse/DOC-406
- [x] inc version number

### CODE REVIEW

**Comment by tbedford** [comment]
@ginotoro - I believe this should cover the recent changes. FYI.

**Comment by ginotoro** [comment]
> @ginotoro - I believe this should cover the recent changes. FYI.

Great. It does.

**Review by marklewin — APPROVED** [review]
Checked locally using Spectral and LGTM!

**Comment by tbedford** [comment]
Do not merge until feature live.

**Pull request merged**
